//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentStorage
    {
        public string AgentID { get; set; }
        public Nullable<int> PID { get; set; }
        public string PName { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
