//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDetail
    {
        public int DeliveryID { get; set; }
        public string AgentID { get; set; }
        public int PID { get; set; }
        public string Pname { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Company Company { get; set; }
        public virtual Delivery Delivery { get; set; }
    }
}
